kind: Service
apiVersion: v1
metadata:
  name: lolhub-dev-service
  namespace: dev
  labels:
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  selector:
    app: lolhub-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1337