apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lolhub-dev-deployment
  namespace: dev
  labels:
    app: lolhub-dev
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lolhub-dev
  template:
    metadata:
      labels:
        app: lolhub-dev
    spec:
      containers:
      - name: lolhub-server
        image: jungj5/lol-hub:0.0.8-server-dev
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty", "lol-hub-bucket", "/app/data"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/app/data"]