apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lolhub-dev-deployment
  namespace: dev
  labels:
    app: lolhub-dev
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lolhub-dev
  template:
    metadata:
      labels:
        app: lolhub-dev
    spec:
      containers:
      - name: lolhub-server
        image: jungj5/lol-hub:0.0.5-server-dev
        env:
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: content-credentials
              key: YOUTUBE_API_KEY
        - name: TWITCH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: content-credentials
              key: TWITCH_CLIENT_ID
        - name: TWITCH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: content-credentials
              key: TWITCH_CLIENT_SECRET