kind: Service
apiVersion: v1
metadata:
  name: lolhub-service
  namespace: prod
  labels:
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  selector:
    app: lolhub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1337