{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "lolhub-chart.fullname" . }}
  labels:
{{ include "lolhub-chart.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "lolhub-chart.fullname" . }}
          servicePort: 80
{{- end }}
