apiVersion: v1
kind: Service
metadata:
  name: {{ include "lolhub-chart.fullname" . }}
  labels:
{{ include "lolhub-chart.labels" . | indent 4 }}
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  ports:
    - port: 80
      targetPort: 1337
      protocol: TCP
  selector:
    app: {{ include "lolhub-chart.name" . }}
