apiVersion: certmanager.k8s.io/v1alpha1

kind: ClusterIssuer

metadata:

  name: letsencrypt-staging

  namespace: default

spec:

  acme:

    server: https://acme-staging-v02.api.letsencrypt.org/directory

    email: <redacted>

    privateKeySecretRef:

      name: letsencrypt-staging

    dns01:

      providers:

      - name: clouddns

        clouddns:

          serviceAccountSecretRef:

            name: clouddns

            key: clouddns.key.json

          project: lol-hub-238404
